name: Node.js CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CITest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Display .env file
      run: |
            echo "DB_DATABASE=${{ secrets.DB_DATABASE}}" >> .env
            echo "DB_USER=${{ secrets.DB_USER}}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
            echo "DB_DIALECT=${{ secrets.DB_DIALECT}}" >> .env
            cat .env
     
    - name: configuremysql

      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo systemctl start mysql
        sudo systemctl status mysql
        mysql -u ${{ secrets.DB_USER}} -p"${{secrets.DB_PASSWORD}}"
    - name: Run Tests
      run : npm test